### ISSUE TITLE
The Roadmap of the Nushell package manager.

### ISSUE THREAD

**Issue by amtoine** [nushell/nupm#1]
# :warning: Work In Progress :warning: 

projects to check out
- [`kubouch/nuun`: *Nushell Package Manager Exploration*][`kubouch/nuun`]
- [`amtoine/nupm`: *A manager for Nushell packages.*][`amtoine/nupm`]
- [`cargo`: *The Rust package manager*][`cargo`]
- [`rustup`: *The Rust toolchain installer*][`rustup`]
- [`nupac/nupac`: *Nu package manager written entirely in nu & for nu*][`nupac/nupac`]

## :runner: bootstrap ([`rustup`])
> **Note**
> see a prototype [here][`amtoine/nupm` bootstrap]

- [ ] install Nushell without any other requirement -> POSIX compliant / `bash` bootstrap?
- [ ] install `nupm` itself -> see the [`amtoine/nupm` bootstrap]
- [ ] change the version of Nushell with overlays -> [`kubouch/nuun`]

## :wrench: commands to have
- [ ] `nupm new [--script] [--module]`: create a new local package with template files ([`kubouch/nuun`])
- [ ] `nupm init`: initialize an existing local package ([`kubouch/nuun`])
- [ ] `nupm test [--module] [--workspace]`: run unit and integration tests of local package
  \`---> *i think the [`std run-tests`] command just be pulled out of the standard library of Nushell* 
- inspired by [`cargo`]
  - [ ] `nupm install`: ... (different ways of doing this in [`amtoine/nupm`] and [`kubouch/nuun`])
  - [ ] `nupm uninstall`: ...
  - [ ] `nupm update`: ... (prototype in [`amtoine/nupm`])
  - [ ] `nupm bench`: ...
  - [ ] `nupm search`: ...
  - [ ] `nupm publish`: ...
  - [ ] `nupm doc`: ...

## :candy: other nice things to have
- [ ] install plugins
- [ ] have a centralized list of *official* and *community* packages to
  - pull them with `nupm install`
  - search them with `nupm search`
 
## :bulb: concepts to have in mind
- activations from [`amtoine/nupm`]: ...
- overlays from [`kubouch/nuun`]: ...
- require the least amount of user manual intervention
\`---> required things might be
  - using the CLI of `nupm` of course
  - bootstrapping
  - (optional) setting `NUPM_HOME` to change the location of all files (and be XDG-compliant imo)
  - adding a path to `PATH`
  - adding a path to `NU_LIB_DIRS`
  - adding at least one `use` or `overlay use` to bring some commands and modules to the startup scope of the shell
- how do we configure `nupm`
  - config file?
  - environment variables?
  - both?

[`kubouch/nuun`]: https://github.com/kubouch/nuun
[`amtoine/nupm`]: https://github.com/amtoine/nupm
[`cargo`]: https://github.com/rust-lang/cargo
[`rustup`]: https://github.com/rust-lang/rustup
[`nupac/nupac`]: https://github.com/nupac/nupac

[`amtoine/nupm` bootstrap]: https://github.com/amtoine/nupm/blob/main/bootstrap/bootstrap.nu
[`std run-tests`]: https://github.com/nushell/nushell/blob/234ba197d7bd0c7c6aef4b77afff06c5ffd6ae38/crates/nu-std/lib/testing.nu#L308-L437

**Comment by amtoine** [comment]
know packages
- [`nushell/nu_scripts`](https://github.com/nushell/nu_scripts)
- [`amtoine/nu-git-manager`](https://github.com/amtoine/nu-git-manager)
- [`amtoine/nupm`](https://github.com/amtoine/nupm)
- [`amtoine/nu-right-prompt`](https://github.com/amtoine/nu-right-prompt)
- [`amtoine/nu-pomodoro`](https://github.com/amtoine/nu-pomodoro)

candidate packages:
- [`1Kinoti/nu-option`](https://github.com/1Kinoti/nu-option)
- `nu-bookmarks` from https://github.com/nushell/nu_scripts/pull/509

**Comment by colemickens** [comment]
I hope this will include "locking" the same way Cargo does. This will help other package managers that will want to package nushell plugins. I guess this is assuming that remote scripts can include other remote scripts. Having a lockfile mechanism would go a long way to ensuring reproducibility and resilience.

**Comment by uncomfyhalomacro** [comment]
I hope I can see an architecture.md soon or something. :eyes: i want to contribute

**Comment by fdncred** [comment]
I would hope that this would include Windows support since one of nushell's biggest features is being cross-platform.
